Repository simranlotey/Hacktoberfest, pull requests merged in 2024-10, with the labels that each got.

#354 Create wallet_poo
  Python/wallet_poo
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#358 Create Blackjack game.py
  Python/Blackjack game.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#359 outlook email wrapper
  Python/emailwrapper/__init__.py
  Python/emailwrapper/async_email_util.py
  Python/emailwrapper/email_util.py
  Python/emailwrapper/render_template.py
  Python/emailwrapper/tempclean.py
  Simon Game/index.html
  simon Game/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#360 Create insertion-sort.c
  C/insertion-sort.c
Labels: hacktoberfest2024

#363 employee-turnover-prediction
  employee-turnover-prediction/etp.csv
  employee-turnover-prediction/etp.ipynb
  urlShortener-TS/package-lock.json
  urlShortener-TS/package.json
Labels: hacktoberfest-accepted, hacktoberfest2024

#362 prime number
  Python/prime numbers.py
Labels: hacktoberfest-accepted, hacktoberfest2024

#361 Merge Sort in C
  C/mergesort.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#364 fibonacci_series, prime_number_checker, Merge_sort, palindrome_checker, Insertion_sort
  C++/Fibonacci_Series.cpp
  C++/Insertion_Sort.cpp
  C++/Merge_Sort.cpp
  C++/Palindrome_Checker.cpp
  C++/prime_number_checker.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#366 Add solutions for 5 standard algorithmic problems
  .vscode/settings.json
  C++/House Robber.cpp
  C++/Intersection of Two Arrays II.cpp
  C++/Longest Common Prefix.cpp
  C++/Majority Element.cpp
  C++/Middle of the Linked List.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#367 Fixed issue #353 merge sort and #issue352 quick sort addition
  C++/insertionsort.cpp
  C++/mergesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#370 Added lorem-ipsum-generator with a README
  lorem_ipsum_generator/README.md
  lorem_ipsum_generator/index.html
  lorem_ipsum_generator/script.js
  lorem_ipsum_generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#369 Added Segment Tree in C++
  C++/Segment.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#371 Added BigO and Diwali Sales Analysis
  BigO/bigo.ipynb
  BigO/bigo.py
  DiwaliSalesAnalysis/Diwali Sales Data.csv
  DiwaliSalesAnalysis/DiwaliSalesAnalysis.ipynb
  DiwaliSalesAnalysis/DiwaliSalesAnalysis.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#372 image gallery
  Image Gallery/images/back.png
  Image Gallery/images/image-1.png
  Image Gallery/images/image-2.png
  Image Gallery/images/image-3.png
  Image Gallery/images/image-4.png
  Image Gallery/images/image-5.png
  Image Gallery/images/image-6.png
  Image Gallery/images/next.png
  Image Gallery/index.html
  Image Gallery/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#375 Added Tetris Game in Python
  Python/Tetris/tetris.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#376 NKnightsSolver Program added
  java/NKnightsSolver.class
  java/NKnightsSolver.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#378 added rabin karp algorithm
  C++/rabin_karp.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#380 Added Stack using two Queues program
  C++/Stack_using_two_Queues.cpp
Labels: hacktoberfest, hacktoberfest2024

#381 Create guess_the_number.cpp
  C++/guess_the_number.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#382 Rust mini grep
  rust-minigrep/Cargo.lock
  rust-minigrep/Cargo.toml
  rust-minigrep/poem.txt
  rust-minigrep/src/lib.rs
  rust-minigrep/src/main.rs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#383 Dark Mode Feature added
  DakrModeToggle/index.html
  DakrModeToggle/script.js
  DakrModeToggle/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#389 added valid paranthesis problem
  C++/valid_paranthesis_problem.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#388 feat added the pyhton dsa quetion for sentense similarity
  Python/sentense_similarity.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#390 Added Simple Webserver written in C
  C/webserver.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#393 Searching Algorithms in C
  .vscode/settings.json
  C/binarysearch.c
  C/linearsearch.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#394 Created tribonaacci_using_DP.cpp
  C++/tribonaacci_using_DP.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#395 Create AStarAlgorithm
  java/AStarAlgorithm
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#398 Create cartographic_conversion_lambert.py
  Python/cartographic_conversion_lambert.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#396 DSA sort a STACK - Descending
  C++/sortStackDesc.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#401 Create Valid_palindrome.cpp
  C++/Valid_palindrome.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#400 Created a react calculator
  .DS_Store
  React_calculator/.eslintrc.cjs
  React_calculator/.gitignore
  React_calculator/README.md
  React_calculator/index.html
  React_calculator/package-lock.json
  React_calculator/package.json
  React_calculator/public/vite.svg
  React_calculator/src/App.css
  React_calculator/src/App.jsx
  React_calculator/src/assets/react.svg
  React_calculator/src/main.jsx
  React_calculator/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#403 Added continent_quiz.py
  Python/continent_quiz.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#405 Added Guess Indian states game
  Guess States Game/.gitignore
  Guess States Game/indian_states_img.gif
  Guess States Game/main.py
  Guess States Game/states.csv
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#406 Implemented code for pirorityQueue using array
  C++/pirorityQueue.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#408 Create StringHasVowel.java
  java/StringHasVowel.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#412 digit recognizer using python and numPy
  digitrecognizer.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#417 add: adds Two sum python problem
  Python/two-sum.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#416 Created a simple calculator with basic mathematical operations
  PHP/CarsListPanel/Add.php
  PHP/CarsListPanel/Delete.php
  PHP/CarsListPanel/Logout.php
  PHP/CarsListPanel/Update.php
  PHP/CarsListPanel/View.php
  PHP/CarsListPanel/aa-error-check.php
  PHP/CarsListPanel/index.php
  PHP/CarsListPanel/login.php
  PHP/CarsListPanel/pdo.php
  PHP/MathBasicOperations/index.php
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#420 Added Postfix expression evaluation using stack
  C++/postfix-evaluation.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#418 Course Builder
  Course-Builder/.gitignore
  Course-Builder/README.md
  Course-Builder/package-lock.json
  Course-Builder/package.json
  Course-Builder/public/Web.png
  Course-Builder/public/favicon.ico
  Course-Builder/public/index.html
  Course-Builder/public/logo192.png
  Course-Builder/public/logo512.png
  Course-Builder/public/manifest.json
  Course-Builder/public/pdf-icons.png
  Course-Builder/public/robots.txt
  Course-Builder/src/App.css
  Course-Builder/src/App.js
  Course-Builder/src/App.test.js
  Course-Builder/src/Components/AddModule/AddModule.js
  Course-Builder/src/Components/AddModule/Modal.js
  Course-Builder/src/Components/Header/index.js
  Course-Builder/src/Components/ListContainers/ModulesContainer/index.js
  Course-Builder/src/Components/ListContainers/ResourcesContainer/index.js
  Course-Builder/src/Components/Modals/PrimaryModal/index.js
  Course-Builder/src/Components/NotFound/index.js
  Course-Builder/src/Components/utils/index.js
  Course-Builder/src/Layouts/PrimaryLayout/index.js
  Course-Builder/src/Pages/CourseBuilder.js
  Course-Builder/src/Providers/DataProvider/index.js
  Course-Builder/src/index.css
  Course-Builder/src/index.js
  Course-Builder/src/logo.svg
  Course-Builder/src/reportWebVitals.js
  Course-Builder/src/setupTests.js
  Course-Builder/tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#419 Added my project chat with pdf using gemini
  Chat_with_pdf/Gemini_ChatMultipdf.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#423 Added 3d pose estimation
  Python/3d_pose_estimation/3d_pose_estimation.py
  Python/3d_pose_estimation/README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#426 Command-line-Quiz-App
  Command-Line Quiz Application/questions.json
  Command-Line Quiz Application/quiz_app.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#425 Add matrix multiplication in Java
  java/Matrix_Multiplication.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#427 Add String to Integer(atoi) in Java
  java/String_atoi.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#428 3D Rotating Card on Hover with React
  RotatingCard3d/rotating-card-3d/.gitignore
  RotatingCard3d/rotating-card-3d/README.md
  RotatingCard3d/rotating-card-3d/package-lock.json
  RotatingCard3d/rotating-card-3d/package.json
  RotatingCard3d/rotating-card-3d/public/favicon.ico
  RotatingCard3d/rotating-card-3d/public/index.html
  RotatingCard3d/rotating-card-3d/public/logo192.png
  RotatingCard3d/rotating-card-3d/public/logo512.png
  RotatingCard3d/rotating-card-3d/public/manifest.json
  RotatingCard3d/rotating-card-3d/public/robots.txt
  RotatingCard3d/rotating-card-3d/src/App.css
  RotatingCard3d/rotating-card-3d/src/App.js
  RotatingCard3d/rotating-card-3d/src/App.test.js
  RotatingCard3d/rotating-card-3d/src/Card3D.js
  RotatingCard3d/rotating-card-3d/src/index.css
  RotatingCard3d/rotating-card-3d/src/index.js
  RotatingCard3d/rotating-card-3d/src/logo.svg
  RotatingCard3d/rotating-card-3d/src/reportWebVitals.js
  RotatingCard3d/rotating-card-3d/src/setupTests.js
  RotatingCard3d/rotating-card-3d/src/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#429 Added a code in cpp using Floyd's Cycle-Finding Algorithm (also known…
  C++/DetectCycleInLinkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#431 adding q.no 540 - single element in sorted array
  C++/540. Single Element in a Sorted Array.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#434 insertion sort
  C++/height.cpp
  C++/insertion-sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#433 Hollow Diamond in C++
  C++/HollowDiamond.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#432 Hollow Diamond in java
  java/HollowDiamond.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#436 Added java programs
  java/BinarySeacrh.java
  java/BubbleSort.java
  java/LinearSearch.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#437 added radix sort, quick sort and selection sort
  C++/QuickSort.cpp
  C++/radixSort.cpp
  C++/selectionSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024
